name: buem_env
channels:
  - conda-forge
  - default
dependencies:
  - python=3.13
  - cfgrib
  - coincbc
  - cvxpy
  - eccodes
  - flask
  - flask-swagger-ui
  - gunicorn
  - joblib
  - jsonschema
  - matplotlib
  - netcdf4
  - numba
  - numpy
  - openpyxl
  - pandas
  - psutil
  - psycopg2
  - pulp
  - pvlib
  - pyarrow
  - pyproj
  - python-dotenv
  - scipy
  - setuptools-scm>=8
  - sympy
  - xarray
  - pip
  - pip:
    - marshmallow>=4.0.0
    - marshmallow-dataclass>=8.0.0