package:
  name: buem
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0') | replace('v', '') }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.13
    - pip
    - setuptools-scm >=8
  run:
    - python >=3.13
    - cfgrib
    - coinor-cbc  # [linux]
    - cvxpy
    - dask
    - eccodes
    - flask
    - flask-swagger-ui
    - gunicorn    # [linux]
    - joblib
    - jsonschema
    - marshmallow >=4.0.0
    - marshmallow-dataclass >=8.0.0
    - matplotlib
    - netcdf4
    - numba
    - numpy
    - openpyxl
    - pandas
    - pip
    - psutil
    - psycopg2
    - pulp
    - pvlib
    - pyarrow
    - pyproj
    - python-dotenv
    - scipy
    - sympy
    - xarray

about:
  summary: "Building thermal simulation module (ISO 52016-1 5R1C)"
  license: MIT