package:
  name: buem
  version: "0.1.2"

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11
    - matplotlib
    - numpy
    - pandas
    - pvlib
    - scipy
    - sympy
    - openpyxl
    - cvxpy
    - flask
    - python-dotenv
    - gunicorn
    - pulp
    - coinor-cbc # [linux] # native solver only required for Linux containers 
    - gunicorn   # [linux] # server only for container/production

about:
  summary: "Building thermal simulation module (ISO 52016-1 5R1C)"
  license: MIT